apiVersion: v2
appVersion: v1.5.4
description: The Helm chart for Envoy Gateway
home: https://gateway.envoyproxy.io/
icon: https://raw.githubusercontent.com/envoyproxy/gateway/main/site/assets/icons/logo.svg
keywords:
- infra-gateway-api
- envoyproxy
- envoy-infra-gateway-controller
- eg
maintainers:
- name: envoy-infra-gateway-controller-steering-committee
  url: https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
- name: envoy-infra-gateway-controller-maintainers
  url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS
name: infra-gateway-helm
sources:
- https://github.com/envoyproxy/gateway
type: application
version: v1.5.4
